# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to Azure
        run: az login --service-principal --username ${{ secrets.AZ_USER_NAME }} --password ${{ secrets.AZ_PASSWORD }} --tenant ${{ secrets.AZ_TENANT_ID }}
      - name: ARM Template Toolkit (ARM TTK)
        uses: aliencube/arm-ttk-actions@v0.3
        with:
          path: storageaccount
          tests: '"apiVersions Should Be Recent","Resources Should Have Location"'
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:        
          scope: resourcegroup
          subscriptionId: 3dc3cd1a-d5cd-4e3e-a648-b2253048af83         
          resourceGroupName: 32943      
          template: storageaccount/mainTemplate.json
          deploymentMode: Incremental
          deploymentName: deployStorage
          parameters: storageaccount/parameters.json
